"""RubinTV — viewer for Vera C. Rubin Observatory data products."""

try:
    # Generated by setuptools_scm at build/install time (see pyproject.toml).
    from ._version import __version__
except ImportError:  # pragma: no cover - source checkout without an install
    __version__ = "0.0.0+unknown"

__all__ = ["__version__"]
