/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness: the process is running.
         */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: the app is ready to serve traffic.
         */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Status
         * @description Detailed status: readiness plus per-camera history-loading progress.
         */
        get: operations["app_status_api_health_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Location Detail */
        get: operations["get_location_detail_api_locations__location__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera Detail */
        get: operations["get_camera_detail_api_locations__location__cameras__camera__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calendar */
        get: operations["get_calendar_api_locations__location__cameras__camera__calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/dates/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Date Payload */
        get: operations["get_date_payload_api_locations__location__cameras__camera__dates__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/metadata/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metadata */
        get: operations["get_metadata_api_locations__location__cameras__camera__metadata__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event By Key
         * @description Resolve a specific event by its S3 key (validated by the parser).
         */
        get: operations["get_event_by_key_api_locations__location__cameras__camera__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/night-report/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Night Report */
        get: operations["get_night_report_api_locations__location__cameras__camera__night_report__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/admin/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Controls */
        get: operations["get_controls_api_locations__location__admin_controls_get"];
        put?: never;
        /** Set Control */
        post: operations["set_control_api_locations__location__admin_controls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Site Controls */
        get: operations["get_site_controls_api_admin_controls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Menus */
        get: operations["get_admin_menus_api_admin_menus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detectors/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Detectors Config */
        get: operations["get_detectors_config_api_detectors_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Status */
        get: operations["get_admin_status_api_admin_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/controls/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Site Control
         * @description Write an arbitrary control key/value (also used by the menu boxes).
         */
        post: operations["set_site_control_api_admin_controls_set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/witness-detector": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Witness Detector
         * @description Write the witness-detector value to its configured control key.
         */
        post: operations["set_witness_detector_api_admin_witness_detector_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reset-head-node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Head Node
         * @description Trigger a head-node reset by writing its sentinel control value.
         */
        post: operations["reset_head_node_api_admin_reset_head_node_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detectors/{set_name}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart Workers
         * @description Restart a cluster set's workers.
         *
         *     Resolves the set's status key from ``redis_detectors`` config, derives the
         *     reset key (``CLUSTER_STATUS_X`` -> ``RUBINTV_CONTROL_RESET_X``) and writes
         *     the ``reset`` sentinel (matching the original app).
         */
        post: operations["restart_workers_api_detectors__set_name__restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/flush-historical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flush Historical
         * @description Clear the disk + in-memory historical cache and trigger a cold rescan.
         */
        post: operations["flush_historical_api_admin_flush_historical_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/flush-redis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flush Redis
         * @description Danger zone: flush the entire Redis database.
         */
        post: operations["flush_redis_api_admin_flush_redis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/channels/{channel}/{date}/{seq}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proxy Object */
        get: operations["proxy_object_api_locations__location__cameras__camera__channels__channel___date___seq___filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/night-report/{date}/plot/{group}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proxy Night Report Plot */
        get: operations["proxy_night_report_plot_api_locations__location__cameras__camera__night_report__date__plot__group___filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Services
         * @description Current liveness of every reporting RA service.
         */
        get: operations["services_api_health_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/heartbeats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Heartbeat
         * @description Record one liveness beat (fire-and-forget).
         */
        post: operations["post_heartbeat_internal_heartbeats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subapps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Subapps
         * @description Mounted sub-app paths, for the frontend nav.
         */
        get: operations["list_subapps_api_subapps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * App Config
         * @description Deployment bootstrap the SPA reads at startup.
         *
         *     ``site`` is the deployment site name (``RUBINTV_SITE``: ``summit``,
         *     ``usdf-k8s``, ``local`` …). The frontend uses it to label the header —
         *     which processing banner to show and whether to flag a non-prod
         *     instance — since where the *pod* runs is distinct from which location's
         *     bucket is being viewed.
         */
        get: operations["app_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminActionOut
         * @description Generic result of an admin action.
         */
        AdminActionOut: {
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** AdminMenuItemOut */
        AdminMenuItemOut: {
            /** Label */
            label: string;
        };
        /** AdminMenuOut */
        AdminMenuOut: {
            /** Title */
            title: string;
            /** Key */
            key: string;
            /** Items */
            items: components["schemas"]["AdminMenuItemOut"][];
        };
        /** AdminMenusOut */
        AdminMenusOut: {
            /** Menus */
            menus: components["schemas"]["AdminMenuOut"][];
        };
        /**
         * AdminStatusOut
         * @description Site-wide admin panel header info.
         */
        AdminStatusOut: {
            /** Version */
            version: string;
            /** Git Sha */
            git_sha: string;
            /** Commit Date */
            commit_date: string;
            /** Redis Enabled */
            redis_enabled: boolean;
            /** Cache Enabled */
            cache_enabled: boolean;
            /** Witness Detector Key */
            witness_detector_key: string;
        };
        /** CalendarOut */
        CalendarOut: {
            /** Dates */
            dates: string[];
            /**
             * Counts
             * @default {}
             */
            counts: {
                [key: string]: number;
            };
            /**
             * Max Seq
             * @default {}
             */
            max_seq: {
                [key: string]: number;
            };
            /**
             * Channel Latest
             * @default {}
             */
            channel_latest: {
                [key: string]: string;
            };
        };
        /** CameraGroupOut */
        CameraGroupOut: {
            /** Label */
            label: string;
            /** Cameras */
            cameras: components["schemas"]["CameraSummary"][];
        };
        /**
         * CameraOut
         * @description Full camera detail for the camera page header.
         */
        CameraOut: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Online */
            online: boolean;
            /** Logo */
            logo: string | null;
            /** Text Colour */
            text_colour: string | null;
            /** Icon */
            icon: string | null;
            /** Channels */
            channels: components["schemas"]["ChannelOut"][];
            /** Metadata Columns */
            metadata_columns: {
                [key: string]: string;
            };
            /** Locked Columns */
            locked_columns: string[];
            /** Image Viewer Link */
            image_viewer_link: string | null;
            /** Quicklook Viewer Link */
            quicklook_viewer_link: string | null;
            /** Night Report Label */
            night_report_label: string | null;
            /** Night Report Prefix */
            night_report_prefix: string | null;
            /** Copy Row Template */
            copy_row_template: string | null;
            /** Live View */
            live_view: boolean;
            time_since_clock: components["schemas"]["TimeSinceClockOut"] | null;
            /** Extra Buttons */
            extra_buttons: components["schemas"]["ExtraButtonOut"][];
            /** Mosaic View Meta */
            mosaic_view_meta: components["schemas"]["MosaicViewEntryOut"][];
        };
        /** CameraStatus */
        CameraStatus: {
            /** Location */
            location: string;
            /** Camera */
            camera: string;
            /** Recent Ready */
            recent_ready: boolean;
            /** Full Complete */
            full_complete: boolean;
        };
        /**
         * CameraSummary
         * @description Camera as listed under a location (no heavy detail).
         */
        CameraSummary: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Online */
            online: boolean;
            /** Logo */
            logo?: string | null;
            /** Text Colour */
            text_colour?: string | null;
            /**
             * Text Shadow
             * @default false
             */
            text_shadow: boolean;
            /** Latest Date */
            latest_date?: string | null;
        };
        /** ChannelOut */
        ChannelOut: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Label */
            label: string;
            /** Colour */
            colour: string | null;
            /** Text Colour */
            text_colour: string | null;
            /** Icon */
            icon: string | null;
            /** Per Day */
            per_day: boolean;
        };
        /** ControlValue */
        ControlValue: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** ControlsOut */
        ControlsOut: {
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /**
         * DatePayload
         * @description Everything needed to render a camera table for one date.
         */
        DatePayload: {
            /** Date */
            date: string;
            /** Channels */
            channels: {
                [key: string]: (number | string)[];
            };
            /** Extensions */
            extensions: {
                [key: string]: components["schemas"]["ExtInfoOut"];
            };
            /** Per Day */
            per_day: {
                [key: string]: string;
            };
            /** Has Night Report */
            has_night_report: boolean;
        };
        /**
         * DetectorOut
         * @description One configured cluster-status stream (site-wide).
         */
        DetectorOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /** DetectorsConfigOut */
        DetectorsConfigOut: {
            /** Detectors */
            detectors: components["schemas"]["DetectorOut"][];
        };
        /** EventOut */
        EventOut: {
            /** Key */
            key: string;
            /** Camera */
            camera: string;
            /** Day Obs */
            day_obs: string;
            /** Channel */
            channel: string;
            /** Seq Num */
            seq_num: number | string;
            /** Filename */
            filename: string;
            /** Ext */
            ext: string;
        };
        /** ExtInfoOut */
        ExtInfoOut: {
            /** Default */
            default: string | null;
            /** Exceptions */
            exceptions: {
                [key: string]: string;
            };
        };
        /** ExtraButtonOut */
        ExtraButtonOut: {
            /** Title */
            title: string;
            /** Name */
            name: string;
            /** Link Url */
            link_url: string;
            /** Logo */
            logo: string | null;
            /** Text Colour */
            text_colour: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Heartbeat
         * @description One liveness report from an RA service.
         */
        Heartbeat: {
            /** Service */
            service: string;
            /**
             * Ttl
             * @default 30
             */
            ttl: number;
            /** Location */
            location?: string | null;
        };
        /** KeyValuesText */
        KeyValuesText: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "keyvalues";
            /** Title */
            title: string;
            /** Content */
            content: {
                [key: string]: string;
            };
            /** Key */
            key?: string | null;
        };
        /** LinkItem */
        LinkItem: {
            /** Text */
            text: string;
            /** Url */
            url: string;
        };
        /** LinksText */
        LinksText: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "links";
            /** Title */
            title: string;
            /** Content */
            content: components["schemas"]["LinkItem"][];
            /** Key */
            key?: string | null;
        };
        /** LiveResponse */
        LiveResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** LocationOut */
        LocationOut: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Logo */
            logo: string | null;
            /** Text Colour */
            text_colour: string | null;
            /** Text Shadow */
            text_shadow: boolean;
            /** Is Teststand */
            is_teststand: boolean;
            /** Has Cluster Status */
            has_cluster_status: boolean;
            /** Services */
            services: string[];
            /** Camera Groups */
            camera_groups: components["schemas"]["CameraGroupOut"][];
        };
        /** LocationSummary */
        LocationSummary: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Logo */
            logo?: string | null;
            /** Text Colour */
            text_colour?: string | null;
            /**
             * Text Shadow
             * @default false
             */
            text_shadow: boolean;
            /**
             * Is Teststand
             * @default false
             */
            is_teststand: boolean;
            /**
             * Has Cluster Status
             * @default false
             */
            has_cluster_status: boolean;
        };
        /** MosaicViewEntryOut */
        MosaicViewEntryOut: {
            /** Channel */
            channel: string;
            /** Media Type */
            media_type: string;
            /** Meta Columns */
            meta_columns: string[];
        };
        /** MultilineText */
        MultilineText: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "multiline";
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Key */
            key?: string | null;
        };
        /** NightReportOut */
        NightReportOut: {
            /** Date */
            date: string;
            /** Exists */
            exists: boolean;
            /** Text */
            text: (components["schemas"]["MultilineText"] | components["schemas"]["KeyValuesText"] | components["schemas"]["LinksText"])[];
            /** Plots */
            plots: components["schemas"]["PlotOut"][];
        };
        /** PlotOut */
        PlotOut: {
            /** Key */
            key: string;
            /** Group */
            group: string;
            /** Filename */
            filename: string;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Ready */
            ready: boolean;
        };
        /** ServicesResponse */
        ServicesResponse: {
            /** Services */
            services: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
        };
        /** StatusResponse */
        StatusResponse: {
            /** Ready */
            ready: boolean;
            /** Cache Enabled */
            cache_enabled: boolean;
            /** Warm Start */
            warm_start: boolean;
            /** Historical Loading */
            historical_loading: boolean;
            /** S3 Healthy */
            s3_healthy: boolean;
            /** S3 Slow */
            s3_slow: boolean;
            /** Cameras */
            cameras: components["schemas"]["CameraStatus"][];
        };
        /** TimeSinceClockOut */
        TimeSinceClockOut: {
            /** Label */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    app_status_api_health_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    list_locations_api_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationSummary"][];
                };
            };
        };
    };
    get_location_detail_api_locations__location__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_detail_api_locations__location__cameras__camera__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera: string;
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_api_locations__location__cameras__camera__calendar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
                camera: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_date_payload_api_locations__location__cameras__camera__dates__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                location: string;
                camera: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatePayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metadata_api_locations__location__cameras__camera__metadata__date__get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
            };
            path: {
                date: string;
                location: string;
                camera: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_by_key_api_locations__location__cameras__camera__events_get: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path: {
                camera: string;
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_night_report_api_locations__location__cameras__camera__night_report__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                location: string;
                camera: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NightReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_controls_api_locations__location__admin_controls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_control_api_locations__location__admin_controls_post: {
        parameters: {
            query?: never;
            header?: {
                "x-auth-user"?: string | null;
            };
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlValue"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlValue"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_site_controls_api_admin_controls_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlsOut"];
                };
            };
        };
    };
    get_admin_menus_api_admin_menus_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMenusOut"];
                };
            };
        };
    };
    get_detectors_config_api_detectors_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectorsConfigOut"];
                };
            };
        };
    };
    get_admin_status_api_admin_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatusOut"];
                };
            };
        };
    };
    set_site_control_api_admin_controls_set_post: {
        parameters: {
            query?: never;
            header?: {
                "x-auth-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlValue"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_witness_detector_api_admin_witness_detector_post: {
        parameters: {
            query?: never;
            header?: {
                "x-auth-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlValue"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_head_node_api_admin_reset_head_node_post: {
        parameters: {
            query?: never;
            header?: {
                "x-auth-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_workers_api_detectors__set_name__restart_post: {
        parameters: {
            query?: never;
            header?: {
                "x-auth-user"?: string | null;
            };
            path: {
                set_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flush_historical_api_admin_flush_historical_post: {
        parameters: {
            query?: never;
            header?: {
                "x-auth-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flush_redis_api_admin_flush_redis_post: {
        parameters: {
            query?: never;
            header?: {
                "x-auth-user"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proxy_object_api_locations__location__cameras__camera__channels__channel___date___seq___filename__get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
                Range?: string | null;
            };
            path: {
                channel: string;
                seq: string;
                filename: string;
                date: string;
                location: string;
                camera: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proxy_night_report_plot_api_locations__location__cameras__camera__night_report__date__plot__group___filename__get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
                Range?: string | null;
            };
            path: {
                group: string;
                filename: string;
                date: string;
                location: string;
                camera: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    services_api_health_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicesResponse"];
                };
            };
        };
    };
    post_heartbeat_internal_heartbeats_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Heartbeat"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subapps_api_subapps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    app_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
