/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness: the process is running.
         */
        get: operations["live_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness: the app is ready to serve traffic.
         */
        get: operations["ready_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Location Detail */
        get: operations["get_location_detail_api_locations__location__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera Detail */
        get: operations["get_camera_detail_api_locations__location__cameras__camera__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calendar */
        get: operations["get_calendar_api_locations__location__cameras__camera__calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/dates/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Date Payload */
        get: operations["get_date_payload_api_locations__location__cameras__camera__dates__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/metadata/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metadata */
        get: operations["get_metadata_api_locations__location__cameras__camera__metadata__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event By Key
         * @description Resolve a specific event by its S3 key (validated by the parser).
         */
        get: operations["get_event_by_key_api_locations__location__cameras__camera__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/night-report/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Night Report */
        get: operations["get_night_report_api_locations__location__cameras__camera__night_report__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/admin/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Controls */
        get: operations["get_controls_api_locations__location__admin_controls_get"];
        put?: never;
        /** Set Control */
        post: operations["set_control_api_locations__location__admin_controls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/locations/{location}/cameras/{camera}/channels/{channel}/{date}/{seq}/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Proxy Object */
        get: operations["proxy_object_api_locations__location__cameras__camera__channels__channel___date___seq___filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalendarOut */
        CalendarOut: {
            /** Dates */
            dates: string[];
        };
        /** CameraGroupOut */
        CameraGroupOut: {
            /** Label */
            label: string;
            /** Cameras */
            cameras: components["schemas"]["CameraSummary"][];
        };
        /**
         * CameraOut
         * @description Full camera detail for the camera page header.
         */
        CameraOut: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Online */
            online: boolean;
            /** Channels */
            channels: components["schemas"]["ChannelOut"][];
            /** Metadata Columns */
            metadata_columns: {
                [key: string]: string;
            };
            /** Image Viewer Link */
            image_viewer_link: string | null;
            /** Has Mosaic */
            has_mosaic: boolean;
            /** Has Allsky */
            has_allsky: boolean;
        };
        /**
         * CameraSummary
         * @description Camera as listed under a location (no heavy detail).
         */
        CameraSummary: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Online */
            online: boolean;
        };
        /** ChannelOut */
        ChannelOut: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Label */
            label: string;
            /** Colour */
            colour: string | null;
            /** Icon */
            icon: string | null;
            /** Per Day */
            per_day: boolean;
        };
        /** ControlValue */
        ControlValue: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** ControlsOut */
        ControlsOut: {
            /** Values */
            values: {
                [key: string]: string;
            };
        };
        /**
         * DatePayload
         * @description Everything needed to render a camera table for one date.
         */
        DatePayload: {
            /** Date */
            date: string;
            /** Channels */
            channels: {
                [key: string]: (number | string)[];
            };
            /** Extensions */
            extensions: {
                [key: string]: components["schemas"]["ExtInfoOut"];
            };
            /** Per Day */
            per_day: {
                [key: string]: string;
            };
            /** Metadata */
            metadata: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Has Night Report */
            has_night_report: boolean;
        };
        /** EventOut */
        EventOut: {
            /** Key */
            key: string;
            /** Camera */
            camera: string;
            /** Day Obs */
            day_obs: string;
            /** Channel */
            channel: string;
            /** Seq Num */
            seq_num: number | string;
            /** Filename */
            filename: string;
            /** Ext */
            ext: string;
        };
        /** ExtInfoOut */
        ExtInfoOut: {
            /** Default */
            default: string | null;
            /** Exceptions */
            exceptions: {
                [key: string]: string;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiveResponse */
        LiveResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** LocationOut */
        LocationOut: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Camera Groups */
            camera_groups: components["schemas"]["CameraGroupOut"][];
        };
        /** LocationSummary */
        LocationSummary: {
            /** Name */
            name: string;
            /** Title */
            title: string;
        };
        /** NightReportOut */
        NightReportOut: {
            /** Date */
            date: string;
            /** Exists */
            exists: boolean;
            /** Text */
            text: {
                [key: string]: unknown;
            }[];
            /** Plots */
            plots: components["schemas"]["PlotOut"][];
        };
        /** PlotOut */
        PlotOut: {
            /** Key */
            key: string;
            /** Group */
            group: string;
            /** Filename */
            filename: string;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Ready */
            ready: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    ready_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    list_locations_api_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationSummary"][];
                };
            };
        };
    };
    get_location_detail_api_locations__location__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_detail_api_locations__location__cameras__camera__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera: string;
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_api_locations__location__cameras__camera__calendar_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
                camera: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_date_payload_api_locations__location__cameras__camera__dates__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                location: string;
                camera: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatePayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metadata_api_locations__location__cameras__camera__metadata__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                location: string;
                camera: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_by_key_api_locations__location__cameras__camera__events_get: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path: {
                camera: string;
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_night_report_api_locations__location__cameras__camera__night_report__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                location: string;
                camera: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NightReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_controls_api_locations__location__admin_controls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_control_api_locations__location__admin_controls_post: {
        parameters: {
            query?: never;
            header?: {
                "x-auth-user"?: string | null;
            };
            path: {
                location: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlValue"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlValue"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    proxy_object_api_locations__location__cameras__camera__channels__channel___date___seq___filename__get: {
        parameters: {
            query?: never;
            header?: {
                "if-none-match"?: string | null;
                Range?: string | null;
            };
            path: {
                channel: string;
                seq: string;
                filename: string;
                date: string;
                location: string;
                camera: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
